/* For Debugging */
var _debug_enabled = true;

// From the ngl Overlay Plugin
var debug_event = {
    "type": "CombatData",
    "Encounter": {
        "n": "\n",
        "t": "\t",
        "title": "Rukshs Dheem",
        "duration": "06:58",
        "DURATION": "418",
        "damage": "14090904",
        "damage-m": "14.09",
        "damage-*": "14.09M",
        "DAMAGE-k": "14091",
        "DAMAGE-m": "14",
        "DAMAGE-b": "0",
        "DAMAGE-*": "14M",
        "dps": "33710.30",
        "dps-*": "dps-*",
        "DPS": "33710",
        "DPS-k": "34",
        "DPS-m": "DPS-m",
        "DPS-*": "33K",
        "encdps": "33710.30",
        "encdps-*": "33.71K",
        "ENCDPS": "33710",
        "ENCDPS-k": "34",
        "ENCDPS-m": "0",
        "ENCDPS-*": "33K",
        "hits": "1534",
        "crithits": "365",
        "crithit%": "0%",
        "misses": "0",
        "hitfailed": "0",
        "swings": "1534",
        "tohit": "100.00",
        "TOHIT": "100",
        "maxhit": "Limit Break-Bladedance-353150",
        "MAXHIT": "Limit Break-353150",
        "maxhit-*": "Limit Break-Bladedance-353.15K",
        "MAXHIT-*": "Limit Break-353K",
        "healed": "2353852",
        "enchps": "5631.22",
        "enchps-*": "5.63K",
        "ENCHPS": "5631",
        "ENCHPS-k": "6",
        "ENCHPS-m": "0",
        "ENCHPS-*": "5631",
        "heals": "241",
        "critheals": "365",
        "critheal%": "0%",
        "cures": "0",
        "maxheal": "Lucy Morgenstern-Equilibrium-46147",
        "MAXHEAL": "Lucy Morgenstern-46147",
        "maxhealward": "Lucy Morgenstern-Equilibrium-46147",
        "MAXHEALWARD": "Lucy Morgenstern-46147",
        "maxheal-*": "Lucy Morgenstern-Equilibrium-46.15K",
        "MAXHEAL-*": "Lucy Morgenstern-46K",
        "maxhealward-*": "Lucy Morgenstern-Equilibrium-46.15K",
        "MAXHEALWARD-*": "Lucy Morgenstern-46K",
        "damagetaken": "2459894",
        "damagetaken-*": "2.46M",
        "healstaken": "2365999",
        "healstaken-*": "2.37M",
        "powerdrain": "0",
        "powerdrain-*": "0",
        "powerheal": "0",
        "powerheal-*": "0",
        "kills": "15",
        "deaths": "0",
        "CurrentZoneName": "Anamnesis Anyder",
        "Last10DPS": "75634",
        "Last30DPS": "45963",
        "Last60DPS": "40038"
    },
    "Combatant": {
        "YOU": {
            "n": "\n",
            "t": "\t",
            "name": "YOU",
            "duration": "06:58",
            "DURATION": "418",
            "damage": "6881796",
            "damage-m": "6.88",
            "damage-b": "0.01",
            "damage-*": "6.88M",
            "DAMAGE-k": "6882",
            "DAMAGE-m": "7",
            "DAMAGE-b": "0",
            "DAMAGE-*": "6881K",
            "damage%": "48%",
            "dps": "16463.63",
            "dps-*": "16.46K",
            "DPS": "16464",
            "DPS-k": "16",
            "DPS-m": "0",
            "DPS-*": "16K",
            "encdps": "16463.63",
            "encdps-*": "16.46K",
            "ENCDPS": "16464",
            "ENCDPS-k": "16",
            "ENCDPS-m": "0",
            "ENCDPS-*": "16K",
            "hits": "775",
            "crithits": "169",
            "crithit%": "22%",
            "crittypes": "0.0%L - 0.0%F - 0.0%M",
            "misses": "0",
            "hitfailed": "0",
            "swings": "775",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Air Anchor-63221",
            "MAXHIT": "63221",
            "maxhit-*": "Air Anchor-63.22K",
            "MAXHIT-*": "63K",
            "healed": "0",
            "healed%": "0%",
            "enchps": "0.00",
            "enchps-*": "0",
            "ENCHPS": "0",
            "ENCHPS-k": "0",
            "ENCHPS-m": "0",
            "ENCHPS-*": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "0",
            "cures": "0",
            "maxheal": "",
            "MAXHEAL": "",
            "maxhealward": "",
            "MAXHEALWARD": "",
            "maxheal-*": "",
            "MAXHEAL-*": "",
            "maxhealward-*": "",
            "MAXHEALWARD-*": "",
            "damagetaken": "329083",
            "damagetaken-*": "329.08K",
            "healstaken": "256814",
            "healstaken-*": "256.81K",
            "powerdrain": "0",
            "powerdrain-*": "0",
            "powerheal": "0",
            "powerheal-*": "0",
            "kills": "5",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "Last10DPS": "0",
            "Last30DPS": "2789",
            "Last60DPS": "9616",
            "Job": "Mch",
            "ParryPct": "20%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%",
            "DirectHitPct": "32%",
            "DirectHitCount": "246",
            "CritDirectHitCount": "74",
            "CritDirectHitPct": "10%",
            "overHeal": "0",
            "damageShield": "0",
            "absorbHeal": "0",
            "JobOrName": "Mch"
        },
        "Lucy Morgenstern": {
            "n": "\n",
            "t": "\t",
            "name": "Lucy Morgenstern",
            "duration": "06:57",
            "DURATION": "417",
            "damage": "2914442",
            "damage-m": "2.91",
            "damage-b": "0.00",
            "damage-*": "2.91M",
            "DAMAGE-k": "2914",
            "DAMAGE-m": "3",
            "DAMAGE-b": "0",
            "DAMAGE-*": "2914K",
            "damage%": "20%",
            "dps": "6989.07",
            "dps-*": "6.99K",
            "DPS": "6989",
            "DPS-k": "7",
            "DPS-m": "0",
            "DPS-*": "6989",
            "encdps": "6972.35",
            "encdps-*": "6.97K",
            "ENCDPS": "6972",
            "ENCDPS-k": "7",
            "ENCDPS-m": "0",
            "ENCDPS-*": "6972",
            "hits": "381",
            "crithits": "132",
            "crithit%": "35%",
            "crittypes": "0.0%L - 0.0%F - 0.0%M",
            "misses": "0",
            "hitfailed": "0",
            "swings": "381",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Inner Chaos-51156",
            "MAXHIT": "51156",
            "maxhit-*": "Inner Chaos-51.16K",
            "MAXHIT-*": "51K",
            "healed": "194430",
            "healed%": "8%",
            "enchps": "465.14",
            "enchps-*": "465",
            "ENCHPS": "465",
            "ENCHPS-k": "0",
            "ENCHPS-m": "0",
            "ENCHPS-*": "465",
            "critheals": "3",
            "critheal%": "23%",
            "heals": "13",
            "cures": "0",
            "maxheal": "Equilibrium-46147",
            "MAXHEAL": "46147",
            "maxhealward": "Equilibrium-46147",
            "MAXHEALWARD": "46147",
            "maxheal-*": "Equilibrium-46.15K",
            "MAXHEAL-*": "46.15K",
            "maxhealward-*": "Equilibrium-46.15K",
            "MAXHEALWARD-*": "46.15K",
            "damagetaken": "1543977",
            "damagetaken-*": "1.54M",
            "healstaken": "1456724",
            "healstaken-*": "1.46M",
            "powerdrain": "0",
            "powerdrain-*": "0",
            "powerheal": "0",
            "powerheal-*": "0",
            "kills": "5",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "Last10DPS": "0",
            "Last30DPS": "4487",
            "Last60DPS": "5575",
            "Job": "War",
            "ParryPct": "9%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%",
            "DirectHitPct": "12%",
            "DirectHitCount": "44",
            "CritDirectHitCount": "44",
            "CritDirectHitPct": "12%",
            "overHeal": "0",
            "damageShield": "0",
            "absorbHeal": "0",
            "JobOrName": "War"
        },
        "Tyon' Hinamori": {
            "n": "\n",
            "t": "\t",
            "name": "Tyon' Hinamori",
            "duration": "06:54",
            "DURATION": "414",
            "damage": "2867381",
            "damage-m": "2.87",
            "damage-b": "0.00",
            "damage-*": "2.87M",
            "DAMAGE-k": "2867",
            "DAMAGE-m": "3",
            "DAMAGE-b": "0",
            "DAMAGE-*": "2867K",
            "damage%": "20%",
            "dps": "6926.04",
            "dps-*": "6.93K",
            "DPS": "6926",
            "DPS-k": "7",
            "DPS-m": "0",
            "DPS-*": "6926",
            "encdps": "6859.76",
            "encdps-*": "6.86K",
            "ENCDPS": "6860",
            "ENCDPS-k": "7",
            "ENCDPS-m": "0",
            "ENCDPS-*": "6859",
            "hits": "256",
            "crithits": "38",
            "crithit%": "15%",
            "crittypes": "0.0%L - 0.0%F - 0.0%M",
            "misses": "0",
            "hitfailed": "0",
            "swings": "256",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Kaeshi: Setsugekka-73082",
            "MAXHIT": "73082",
            "maxhit-*": "Kaeshi: Setsugekka-73.08K",
            "MAXHIT-*": "73K",
            "healed": "12579",
            "healed%": "0%",
            "enchps": "30.09",
            "enchps-*": "30",
            "ENCHPS": "30",
            "ENCHPS-k": "0",
            "ENCHPS-m": "0",
            "ENCHPS-*": "30",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "1",
            "cures": "0",
            "maxheal": "Second Wind-12579",
            "MAXHEAL": "12579",
            "maxhealward": "Second Wind-12579",
            "MAXHEALWARD": "12579",
            "maxheal-*": "Second Wind-12.58K",
            "MAXHEAL-*": "12.58K",
            "maxhealward-*": "Second Wind-12.58K",
            "MAXHEALWARD-*": "12.58K",
            "damagetaken": "363260",
            "damagetaken-*": "363.26K",
            "healstaken": "367669",
            "healstaken-*": "367.67K",
            "powerdrain": "0",
            "powerdrain-*": "0",
            "powerheal": "0",
            "powerheal-*": "0",
            "kills": "5",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "Last10DPS": "0",
            "Last30DPS": "1649",
            "Last60DPS": "4011",
            "Job": "Sam",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "0%",
            "DirectHitPct": "31%",
            "DirectHitCount": "78",
            "CritDirectHitCount": "13",
            "CritDirectHitPct": "5%",
            "overHeal": "0",
            "damageShield": "0",
            "absorbHeal": "0",
            "JobOrName": "Sam"
        },
        "Lumina Fuwako": {
            "n": "\n",
            "t": "\t",
            "name": "Lumina Fuwako",
            "duration": "06:45",
            "DURATION": "405",
            "damage": "1074135",
            "damage-m": "1.07",
            "damage-b": "0.00",
            "damage-*": "1.07M",
            "DAMAGE-k": "1074",
            "DAMAGE-m": "1",
            "DAMAGE-b": "0",
            "DAMAGE-*": "1074K",
            "damage%": "7%",
            "dps": "2652.19",
            "dps-*": "2.65K",
            "DPS": "2652",
            "DPS-k": "3",
            "DPS-m": "0",
            "DPS-*": "2652",
            "encdps": "2569.70",
            "encdps-*": "2.57K",
            "ENCDPS": "2570",
            "ENCDPS-k": "3",
            "ENCDPS-m": "0",
            "ENCDPS-*": "2569",
            "hits": "121",
            "crithits": "26",
            "crithit%": "21%",
            "crittypes": "0.0%L - 0.0%F - 0.0%M",
            "misses": "0",
            "hitfailed": "0",
            "swings": "121",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Malefic IV-27886",
            "MAXHIT": "27886",
            "maxhit-*": "Malefic IV-27.89K",
            "MAXHIT-*": "27K",
            "healed": "2146843",
            "healed%": "91%",
            "enchps": "5135.99",
            "enchps-*": "5.14K",
            "ENCHPS": "5136",
            "ENCHPS-k": "5",
            "ENCHPS-m": "0",
            "ENCHPS-*": "5135",
            "critheals": "46",
            "critheal%": "20%",
            "heals": "227",
            "cures": "0",
            "maxheal": "Stellar Explosion-44212",
            "MAXHEAL": "44212",
            "maxhealward": "Stellar Explosion-44212",
            "MAXHEALWARD": "44212",
            "maxheal-*": "Stellar Explosion-44.21K",
            "MAXHEAL-*": "44.21K",
            "maxhealward-*": "Stellar Explosion-44.21K",
            "MAXHEALWARD-*": "44.21K",
            "damagetaken": "223574",
            "damagetaken-*": "223.57K",
            "healstaken": "284792",
            "healstaken-*": "284.79K",
            "powerdrain": "0",
            "powerdrain-*": "0",
            "powerheal": "0",
            "powerheal-*": "0",
            "kills": "0",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "Last10DPS": "0",
            "Last30DPS": "1339",
            "Last60DPS": "2678",
            "Job": "Ast",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "100.00",
            "OverHealPct": "11%",
            "DirectHitPct": "12%",
            "DirectHitCount": "14",
            "CritDirectHitCount": "2",
            "CritDirectHitPct": "2%",
            "overHeal": "234443",
            "damageShield": "65832",
            "absorbHeal": "0",
            "JobOrName": "Ast"
        },
        "Limit Break": {
            "n": "\n",
            "t": "\t",
            "name": "Limit Break",
            "duration": "00:00",
            "DURATION": "0",
            "damage": "353150",
            "damage-m": "0.35",
            "damage-b": "0.00",
            "damage-*": "353.15K",
            "DAMAGE-k": "353",
            "DAMAGE-m": "0",
            "DAMAGE-b": "0",
            "DAMAGE-*": "353K",
            "damage%": "2%",
            "dps": "∞",
            "dps-*": "---",
            "DPS": "∞",
            "DPS-k": "∞",
            "DPS-m": "∞",
            "DPS-*": "---",
            "encdps": "844.86",
            "encdps-*": "844",
            "ENCDPS": "845",
            "ENCDPS-k": "1",
            "ENCDPS-m": "0",
            "ENCDPS-*": "844",
            "hits": "1",
            "crithits": "0",
            "crithit%": "0%",
            "crittypes": "-",
            "misses": "0",
            "hitfailed": "0",
            "swings": "1",
            "tohit": "100.00",
            "TOHIT": "100",
            "maxhit": "Bladedance-353150",
            "MAXHIT": "353150",
            "maxhit-*": "Bladedance-353.15K",
            "MAXHIT-*": "353K",
            "healed": "0",
            "healed%": "0%",
            "enchps": "0.00",
            "enchps-*": "0",
            "ENCHPS": "0",
            "ENCHPS-k": "0",
            "ENCHPS-m": "0",
            "ENCHPS-*": "0",
            "critheals": "0",
            "critheal%": "0%",
            "heals": "0",
            "cures": "0",
            "maxheal": "",
            "MAXHEAL": "",
            "maxhealward": "",
            "MAXHEALWARD": "",
            "maxheal-*": "",
            "MAXHEAL-*": "",
            "maxhealward-*": "",
            "MAXHEALWARD-*": "",
            "damagetaken": "0",
            "damagetaken-*": "0",
            "healstaken": "0",
            "healstaken-*": "0",
            "powerdrain": "0",
            "powerdrain-*": "0",
            "powerheal": "0",
            "powerheal-*": "0",
            "kills": "0",
            "deaths": "0",
            "threatstr": "+(0)0/-(0)0",
            "threatdelta": "0",
            "Last10DPS": "---",
            "Last30DPS": "---",
            "Last60DPS": "∞",
            "Job": "",
            "ParryPct": "0%",
            "BlockPct": "0%",
            "IncToHit": "---",
            "OverHealPct": "0%",
            "DirectHitPct": "0%",
            "DirectHitCount": "0",
            "CritDirectHitCount": "0",
            "CritDirectHitPct": "0%",
            "overHeal": "0",
            "damageShield": "0",
            "absorbHeal": "0",
            "JobOrName": "Limit Break"
        }
    },
    "isActive": "false"
};